apiVersion: iot.aws.upbound.io/v1beta1
kind: DomainConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: iot/v1beta1/domainconfiguration
  labels:
    testing.upbound.io/example-name: iot
  name: iot
spec:
  forProvider:
    domainName: iot.example.com
    region: us-west-1
    serverCertificateArnsSelector:
      matchLabels:
        testing.upbound.io/example-name: cert
    serviceType: DATA
---
apiVersion: iot.aws.upbound.io/v1beta1
kind: Certificate
metadata:
  annotations:
    meta.upbound.io/example-id: iot/v1beta1/certificate
  labels:
    testing.upbound.io/example-name: cert
  name: cert
spec:
  forProvider:
    active: true
    region: us-west-1
